# Generated by Django 4.0.6 on 2022-07-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='button_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(default='name', max_length=20),
        ),
    ]
